const keyboardKeysEn = [
  [
    { val: '`', subval: '~' },
    { val: 1, subval: '!' },
    { val: 2, subval: '@' },
    { val: 3, subval: '#' },
    { val: 4, subval: '$' },
    { val: 5, subval: '%' },
    { val: 6, subval: '^' },
    { val: 7, subval: '&' },
    { val: 8, subval: '*' },
    { val: 9, subval: '(' },
    { val: 0, subval: ')' },
    { val: '-', subval: '_' },
    { val: '+', subval: '=' },
    { val: 'Backspace' },
  ],
  [
    { val: 'Tab' },
    { val: 'q' },
    { val: 'w' },
    { val: 'e' },
    { val: 'r' },
    { val: 't' },
    { val: 'y' },
    { val: 'u' },
    { val: 'i' },
    { val: 'o' },
    { val: 'p' },
    { val: '[' },
    { val: ']' },
    { val: '\\', subval: '|' },
    { val: 'Del' },
  ],
  [
    { val: 'Caps Lock' },
    { val: 'a' },
    { val: 's' },
    { val: 'd' },
    { val: 'f' },
    { val: 'g' },
    { val: 'h' },
    { val: 'j' },
    { val: 'k' },
    { val: 'l' },
    { val: ';' },
    { val: "'" },
    { val: 'Enter' },
  ],
  [
    { val: 'Shift' },
    { val: '\\' },
    { val: 'z' },
    { val: 'x' },
    { val: 'c' },
    { val: 'v' },
    { val: 'b' },
    { val: 'n' },
    { val: 'm' },
    { val: '<' },
    { val: '>' },
    { val: '/', subval: '?' },
    { val: '↑' },
    { val: 'Shift' },
  ],
  [
    { val: 'Ctrl' },
    { val: 'Win' },
    { val: 'Alt' },
    { val: 'space' },
    { val: 'Alt' },
    { val: 'Ctrl' },
    { val: '←' },
    { val: '↓' },
    { val: '→' },
  ],
];

export default keyboardKeysEn;
